# Generated by Django 4.2.16 on 2024-10-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('STRING', 'String'), ('DECIMAL', 'Decimal'), ('FOREIGNKEY', 'Foreignkey')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Merchant Category',
                'verbose_name_plural': 'Merchant Categories',
                'db_table': 'merchant_category',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.merchantcategory')),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='DynamicMerchantField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.fieldmodel')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='merchant.merchant')),
            ],
        ),
    ]
