# Generated by Django 4.2.16 on 2024-10-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmerchantfield',
            name='char_field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmerchantfield',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dynamicmerchantfield',
            name='decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='dynamicmerchantfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamicmerchantfield',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
