# Generated by Django 4.2.16 on 2024-10-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_dynamicmerchantfield_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicmerchantfield',
            name='char_field_value',
        ),
        migrations.RemoveField(
            model_name='dynamicmerchantfield',
            name='decimal',
        ),
    ]
