# Generated by Django 4.2.16 on 2024-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_remove_dynamicmerchantfield_char_field_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmerchantfield',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dynamicmerchantfield',
            index=models.Index(fields=['content_type', 'object_id'], name='merchant_dy_content_8f2205_idx'),
        ),
    ]
