# Generated by Django 4.2.16 on 2024-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_alter_dynamicmerchantfield_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='field_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FOREIGNKEY', 'Foreignkey')], max_length=10),
        ),
    ]
