# Generated by Django 4.2.16 on 2024-10-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchant', '0006_alter_fieldmodel_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmerchantfield',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'common')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
