# Generated by Django 4.2.16 on 2024-10-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_alter_dynamicmerchantfield_content_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dynamicmerchantfield',
            name='merchant_dy_content_8f2205_idx',
        ),
        migrations.RemoveField(
            model_name='dynamicmerchantfield',
            name='object_id',
        ),
    ]
