# Generated by Django 4.2.16 on 2024-10-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_remove_dynamicmerchantfield_merchant_dy_content_8f2205_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='merchant.merchantcategory'),
        ),
    ]
